/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.winenergy.bookmark.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Bookmark service. Represents a row in the &quot;WINenergy_Bookmark&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.winenergy.bookmark.model.impl.BookmarkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.winenergy.bookmark.model.impl.BookmarkImpl}.
 * </p>
 *
 * @author Fuping Ma
 * @see Bookmark
 * @see com.winenergy.bookmark.model.impl.BookmarkImpl
 * @see com.winenergy.bookmark.model.impl.BookmarkModelImpl
 * @generated
 */
public interface BookmarkModel extends BaseModel<Bookmark> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bookmark model instance should use the {@link Bookmark} interface instead.
	 */

	/**
	 * Returns the primary key of this bookmark.
	 *
	 * @return the primary key of this bookmark
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bookmark.
	 *
	 * @param primaryKey the primary key of this bookmark
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bookmark ID of this bookmark.
	 *
	 * @return the bookmark ID of this bookmark
	 */
	public long getBookmarkId();

	/**
	 * Sets the bookmark ID of this bookmark.
	 *
	 * @param bookmarkId the bookmark ID of this bookmark
	 */
	public void setBookmarkId(long bookmarkId);

	/**
	 * Returns the name of this bookmark.
	 *
	 * @return the name of this bookmark
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this bookmark.
	 *
	 * @param name the name of this bookmark
	 */
	public void setName(String name);

	/**
	 * Returns the url of this bookmark.
	 *
	 * @return the url of this bookmark
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this bookmark.
	 *
	 * @param url the url of this bookmark
	 */
	public void setUrl(String url);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Bookmark bookmark);

	public int hashCode();

	public CacheModel<Bookmark> toCacheModel();

	public Bookmark toEscapedModel();

	public String toString();

	public String toXmlString();
}