/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.winenergy.bookmark.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.winenergy.bookmark.model.Bookmark;
import com.winenergy.bookmark.service.BookmarkLocalServiceUtil;

/**
 * The extended model base implementation for the Bookmark service. Represents a row in the &quot;WINenergy_Bookmark&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookmarkImpl}.
 * </p>
 *
 * @author Fuping Ma
 * @see BookmarkImpl
 * @see com.winenergy.bookmark.model.Bookmark
 * @generated
 */
public abstract class BookmarkBaseImpl extends BookmarkModelImpl
	implements Bookmark {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bookmark model instance should use the {@link Bookmark} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			BookmarkLocalServiceUtil.addBookmark(this);
		}
		else {
			BookmarkLocalServiceUtil.updateBookmark(this);
		}
	}
}